name: duty-machine-action

on:
  schedule:
    - cron:  '*/5 * * * *'
  # issues:
  #   types: [opened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: nodebe4/duty-machine-action@master
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY: ${{ github.repository }}